# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Herd' do

  	pod 'Firebase/Core'
	pod 'Firebase/Database'
        pod 'SmartDeviceLink', '~> 6.1'
end
